services:
  migrate:
    image: keeply:dev
    pull_policy: never
    build:
      context: .
      target: runner
      args:
        APP_VERSION: dev

  keeply:
    image: keeply:dev
    pull_policy: never
    build:
      context: .
      target: runner
      args:
        APP_VERSION: dev
