"use client";

import { useEffect, useState } from "react";
import { useLiveQuery } from "dexie-react-hooks";
import { get, set } from "idb-keyval";
import { useRouter } from "next/navigation";
import { useLocale, useTranslations } from "next-intl";
import { useTheme } from "next-themes";
import { Archive, Database, Download, Languages, LockKeyhole, Moon, Plus, Sun, Upload } from "lucide-react";
import { toast } from "sonner";
import { clearLocalData, db } from "@/db/local/database";
import { createCategory, createLocation, setCategoryArchived } from "@/db/repositories/taxonomy";
import { exportKeeply, importKeeply } from "@/features/import-export/data-portability";
import type { Locale } from "@/types/domain";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Field, FieldGroup, FieldLabel } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectGroup, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { ToggleGroup, ToggleGroupItem } from "@/components/ui/toggle-group";

export function SettingsPage({ locale }: { locale: string }) {
  const t = useTranslations();
  return <div className="flex flex-col gap-5 pt-10 md:pt-0"><div><h1 className="text-[26px] font-semibold tracking-tight md:text-[30px]">{t("settings.title")}</h1><p className="mt-1 text-sm text-muted-foreground">{t("brand.tagline")}</p></div><Tabs defaultValue="appearance"><TabsList className="max-w-full overflow-x-auto"><TabsTrigger value="appearance">{t("settings.appearance")}</TabsTrigger><TabsTrigger value="taxonomy">{t("settings.categories")}</TabsTrigger><TabsTrigger value="data">{t("settings.data")}</TabsTrigger><TabsTrigger value="privacy">{t("settings.privacy")}</TabsTrigger><TabsTrigger value="about">{t("settings.about")}</TabsTrigger></TabsList><TabsContent value="appearance"><AppearanceSettings locale={locale} /></TabsContent><TabsContent value="taxonomy"><TaxonomySettings /></TabsContent><TabsContent value="data"><DataSettings /></TabsContent><TabsContent value="privacy"><PrivacySettings /></TabsContent><TabsContent value="about"><AboutSettings /></TabsContent></Tabs></div>;
}

function AppearanceSettings({ locale }: { locale: string }) {
  const t = useTranslations(); const router = useRouter(); const { theme, setTheme } = useTheme(); const [density, setDensity] = useState("comfortable"); const [currency, setCurrency] = useState("AUD");
  useEffect(() => { void get<string>("keeply:density").then((value) => value && setDensity(value)); void get<string>("keeply:default-currency").then((value) => value && setCurrency(value)); }, []);
  const changeDensity = (value: string) => { if (!value) return; setDensity(value); document.documentElement.dataset.density = value; void set("keeply:density", value); };
  const changeLocale = (next: Locale) => { router.replace(location.pathname.replace(`/${locale}/`, `/${next}/`)); };
  return <Card><CardHeader><CardTitle>{t("settings.appearance")}</CardTitle><CardDescription>{t("settings.localFirstDescription")}</CardDescription></CardHeader><CardContent><FieldGroup><Field><FieldLabel>{t("settings.theme")}</FieldLabel><ToggleGroup type="single" value={theme} onValueChange={(value) => value && setTheme(value)} variant="outline" className="w-full"><ToggleGroupItem value="system" className="flex-1">{t("settings.system")}</ToggleGroupItem><ToggleGroupItem value="light" className="flex-1"><Sun />{t("settings.light")}</ToggleGroupItem><ToggleGroupItem value="dark" className="flex-1"><Moon />{t("settings.dark")}</ToggleGroupItem></ToggleGroup></Field><Field><FieldLabel>{t("settings.density")}</FieldLabel><ToggleGroup type="single" value={density} onValueChange={changeDensity} variant="outline" className="w-full"><ToggleGroupItem value="comfortable" className="flex-1">{t("settings.comfortable")}</ToggleGroupItem><ToggleGroupItem value="compact" className="flex-1">{t("settings.compact")}</ToggleGroupItem></ToggleGroup></Field><Field><FieldLabel>{t("settings.language")}</FieldLabel><ToggleGroup type="single" value={locale} onValueChange={(value) => value && changeLocale(value as Locale)} variant="outline" className="w-full"><ToggleGroupItem value="zh-CN" className="flex-1"><Languages />简体中文</ToggleGroupItem><ToggleGroupItem value="en" className="flex-1"><Languages />English</ToggleGroupItem></ToggleGroup></Field><Field><FieldLabel>{t("settings.defaultCurrency")}</FieldLabel><Select value={currency} onValueChange={(value) => { setCurrency(value); void set("keeply:default-currency", value); }}><SelectTrigger aria-label={t("settings.defaultCurrency")} className="w-full sm:w-56"><SelectValue /></SelectTrigger><SelectContent><SelectGroup>{["CNY", "AUD", "USD", "EUR", "GBP", "JPY", "HKD", "SGD", "CAD", "NZD"].map((code) => <SelectItem key={code} value={code}>{code}</SelectItem>)}</SelectGroup></SelectContent></Select></Field></FieldGroup></CardContent></Card>;
}

function TaxonomySettings() {
  const t = useTranslations(); const locale = useLocale(); const data = useLiveQuery(async () => ({ categories: await db.categories.orderBy("sortOrder").toArray(), locations: await db.locations.orderBy("sortOrder").toArray() }), []); const [categoryName, setCategoryName] = useState(""); const [locationName, setLocationName] = useState("");
  const addCategory = async () => { if (!categoryName.trim()) return; await createCategory(categoryName.trim(), (data?.categories.length ?? 0) + 100); setCategoryName(""); };
  const addLocation = async () => { if (!locationName.trim()) return; await createLocation(locationName.trim(), data?.locations.length ?? 0); setLocationName(""); };
  return <div className="grid gap-5 lg:grid-cols-2"><Card><CardHeader><CardTitle>{t("settings.categories")}</CardTitle></CardHeader><CardContent className="flex flex-col gap-4"><div className="flex gap-2"><Input value={categoryName} onChange={(event) => setCategoryName(event.target.value)} placeholder={t("form.category")} /><Button size="icon" aria-label={t("common.add")} onClick={() => void addCategory()}><Plus /></Button></div><div className="max-h-[460px] overflow-y-auto rounded-lg border">{data?.categories.map((category) => <div key={category.id} className="flex min-h-12 items-center justify-between border-b px-3 last:border-b-0"><span className="text-sm">{locale === "zh-CN" ? category.nameZh : category.nameEn}</span><Switch checked={!category.isArchived} onCheckedChange={(checked) => void setCategoryArchived(category.id, !checked)} aria-label={t("settings.categories")} /></div>)}</div></CardContent></Card><Card><CardHeader><CardTitle>{t("settings.locations")}</CardTitle></CardHeader><CardContent className="flex flex-col gap-4"><div className="flex gap-2"><Input value={locationName} onChange={(event) => setLocationName(event.target.value)} placeholder={t("form.location")} /><Button size="icon" aria-label={t("common.add")} onClick={() => void addLocation()}><Plus /></Button></div><div className="rounded-lg border">{data?.locations.length ? data.locations.map((location) => <div key={location.id} className="flex min-h-12 items-center border-b px-3 text-sm last:border-b-0">{location.name}</div>) : <p className="p-6 text-center text-sm text-muted-foreground">{t("items.noResults")}</p>}</div></CardContent></Card></div>;
}

function DataSettings() {
  const t = useTranslations(); const [clearOpen, setClearOpen] = useState(false); const [confirmation, setConfirmation] = useState(""); const inputId = "keeply-import";
  const importFile = async (file?: File) => { if (!file) return; try { const count = await importKeeply(file); toast.success(t("form.saved"), { description: `${count}` }); } catch { toast.error(t("errors.generic"), { description: t("errors.dataSafe") }); } };
  return <Card><CardHeader><CardTitle>{t("settings.data")}</CardTitle><CardDescription>{t("settings.localFirstDescription")}</CardDescription></CardHeader><CardContent className="flex flex-col gap-6"><section><h3 className="mb-3 text-sm font-semibold">{t("settings.exportData")}</h3><div className="flex flex-wrap gap-2">{(["json", "csv", "xlsx", "zip"] as const).map((format) => <Button key={format} variant="outline" onClick={() => void exportKeeply(format)}><Download data-icon="inline-start" />{format.toUpperCase()}</Button>)}</div></section><section><h3 className="mb-3 text-sm font-semibold">{t("settings.importData")}</h3><input id={inputId} className="sr-only" type="file" accept=".json,.csv,.xlsx,.xls,.zip" onChange={(event) => void importFile(event.target.files?.[0])} /><Button asChild variant="outline"><label htmlFor={inputId}><Upload data-icon="inline-start" />{t("settings.importData")}</label></Button></section><section className="border-t pt-5"><Button variant="destructive" onClick={() => setClearOpen(true)}>{t("settings.clearData")}</Button></section><AlertDialog open={clearOpen} onOpenChange={setClearOpen}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{t("settings.clearData")}</AlertDialogTitle><AlertDialogDescription>{t("settings.clearConfirm")}</AlertDialogDescription></AlertDialogHeader><Input value={confirmation} onChange={(event) => setConfirmation(event.target.value)} autoComplete="off" /><AlertDialogFooter><AlertDialogCancel>{t("common.cancel")}</AlertDialogCancel><AlertDialogAction disabled={confirmation !== "DELETE"} onClick={() => void clearLocalData().then(() => { setConfirmation(""); toast.success(t("common.done")); })}>{t("common.delete")}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></CardContent></Card>;
}

function PrivacySettings() {
  const t = useTranslations(); const [enabled, setEnabled] = useState(false);
  useEffect(() => { void get<boolean>("keeply:privacy-blur").then((value) => setEnabled(Boolean(value))); const onVisibility = () => { if (document.hidden && enabled) document.body.classList.add("privacy-active"); else document.body.classList.remove("privacy-active"); }; document.addEventListener("visibilitychange", onVisibility); return () => document.removeEventListener("visibilitychange", onVisibility); }, [enabled]);
  return <Card><CardHeader><CardTitle>{t("settings.privacy")}</CardTitle><CardDescription>{t("settings.localFirstDescription")}</CardDescription></CardHeader><CardContent><div className="flex items-center justify-between gap-5 rounded-xl border p-4"><div><p className="text-sm font-medium">{t("settings.privacyBlur")}</p><p className="mt-1 text-xs text-muted-foreground">{t("sync.safe")}</p></div><Switch checked={enabled} onCheckedChange={(checked) => { setEnabled(checked); void set("keeply:privacy-blur", checked); }} /></div></CardContent></Card>;
}

function AboutSettings() { const t = useTranslations(); return <Card><CardHeader><CardTitle>{t("brand.name")}</CardTitle><CardDescription>{t("brand.tagline")}</CardDescription></CardHeader><CardContent className="grid gap-3 sm:grid-cols-3"><div className="rounded-xl border p-4"><Database className="mb-3 size-5 text-primary" /><p className="text-sm font-medium">{t("settings.localFirst")}</p></div><div className="rounded-xl border p-4"><LockKeyhole className="mb-3 size-5 text-primary" /><p className="text-sm font-medium">{t("settings.privacy")}</p></div><div className="rounded-xl border p-4"><Archive className="mb-3 size-5 text-primary" /><p className="text-sm font-medium">{t("settings.backup")}</p></div><p className="text-xs text-muted-foreground sm:col-span-3">{t("settings.version")}</p></CardContent></Card>; }
